[build]
builder = "NIXPACKS"
buildCommand = "cd backend-code/backend && npm install --omit=dev"

[deploy]
startCommand = "cd backend-code/backend && npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 30
